tasks:
  - name: Set up dev environment
    before: |
      npm install -g gatsby-cli
      npm install
    command:
      gatsby develop

ports:
  - port: 8000
    onOpen: open-preview
    
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
    addBadge: false